<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <Version>1.2.1.0</Version>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AICShared\AICShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.dll" />
    <Resource Include="Resources\app.ico" />
    <Resource Include="Resources\mascot.png" />
    <Resource Include="Resources\stickers_sheet.png" />
  </ItemGroup>
</Project>
